### ISSUE TITLE
Zookal active during installation

### ISSUE THREAD

**Issue by mr-jingles** [Zookal/magento-mock#12]
Is there any way to get rid of errors during the installation process?

I get the following error with an empty database - when Magento is running its setup scripts and Magento Mock is active.

/Mage/Catalog/sql/catalog_setup/install-1.6.0.0.php" - Can't retrieve entity config: customer/entity

**Comment by mr-jingles** [comment]
I am using the Magento as PIM XML

**Comment by SchumacherFM** [comment]
Hi. I have no idea what you are doing. 
I don't know any environment settings from your installation ...

Sorry can't help, except that you always can uninstall the mock module.

**Comment by chrisjz** [comment]
Closed due to no new comments for a while.
