### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by zlep** [Zookal/magento-mock#20]
Hi, I just wanted to ask how I could configure this module. I read the description and it says "works out of the box", so does this mean I just put the app folder in my magento directory?

But then I read on your website:

"At Zookal we have the following modules disabled: Mage_AdminNotification, Mage_Authorizenet, Mage_Backup, Mage_Captcha, Mage_Compiler, Mage_Connect, Mage_GoogleCheckout, Mage_GoogleBase, Mage_Install, Mage_Log, Mage_Paypal, Mage_PaypalUk, Mage_Poll, Mage_ProductAlert, Mage_Review, Mage_Rating, Mage_Rss, Mage_Sendfriend, Mage_Tag, Mage_Usa, Mage_Wishlist, Mage_XmlConnect, Phoenix_Moneybookers."

Are these the default disabled modules? But what if I need one of these modules like Mage_Paypal?

Thanks

**Comment by SchumacherFM** [comment]
Hi,

there is no configuration it simply catches a call to a missing class/method or class constant.

> Are these the default disabled modules? 

Nope. The mock module runs at last in the autoloader function.

**Comment by zlep** [comment]
Sorry, but I still don't get it. So how do I define which modules I want to disable? Let's say I want to disable Mage_RSS, Mage_Bundle, Mage_Tag, Mage_Newsletter because I don't need them (and in best case get a better performance if they are disabled). How would I disable exactly these modules with your extension?

**Comment by heldchen** [comment]
you disable them in their individual files within etc/modules

**Comment by zlep** [comment]
Got it, thanks.
Could I also create a new file 'yz_DisabledModules.xml' and disable the modules in this file instead of editing the core files? I guess that's best practice at least.

Thanks

**Comment by heldchen** [comment]
yeah, that's what I'm doing: `zzz_DisabledModules.xml`

**Comment by zlep** [comment]
Ok, but that does not work for most of the Mage_xxx modules, does it? Because Mage_Review, Mage_Rating, Mage_Rss, Mage_Sendfriend, and so on are all in Mage_All.xml (which also contains important Mage_xxx modules like Mage_Core. So I cannot delete the file Mage_All.xml.
